//
//  DetailProductViewController.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import BarcodeScanner

class DetailProductViewController: UIViewController, DetailProductViewProtocol {

	var presenter: DetailProductPresenterProtocol?
    @IBOutlet weak var tfBarcode: UITextField!

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction  func btnBarCodeTapped() {
        let vcBarCode = makeBarcodeScannerViewController()
        vcBarCode.title = "Barcode Scanner"
        present(vcBarCode, animated: true, completion: nil)
    }
    
    private func makeBarcodeScannerViewController() -> BarcodeScannerViewController {
        let viewController = BarcodeScannerViewController()
        viewController.codeDelegate = self
        viewController.errorDelegate = self
        viewController.dismissalDelegate = self
        return viewController
    }

}


// MARK: - BarcodeScannerCodeDelegate

extension DetailProductViewController: BarcodeScannerCodeDelegate {
    func scanner(_ controller: BarcodeScannerViewController, didCaptureCode code: String, type: String) {
        print("Barcode Data: \(code)")
        print("Symbology Type: \(type)")
        tfBarcode.text = code
        controller.dismiss(animated: true, completion: nil)
        
//        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
//            controller.resetWithError()
//        }
    }
}

// MARK: - BarcodeScannerErrorDelegate

extension DetailProductViewController: BarcodeScannerErrorDelegate {
    func scanner(_ controller: BarcodeScannerViewController, didReceiveError error: Error) {
        print(error)
    }
}

// MARK: - BarcodeScannerDismissalDelegate

extension DetailProductViewController: BarcodeScannerDismissalDelegate {
    func scannerDidDismiss(_ controller: BarcodeScannerViewController) {
        controller.dismiss(animated: true, completion: nil)
    }
}
