//
//  DetailProductPresenter.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductPresenter: DetailProductPresenterProtocol, DetailProductInteractorOutputProtocol {

    weak private var view: DetailProductViewProtocol?
    var interactor: DetailProductInteractorInputProtocol?
    private let router: DetailProductWireframeProtocol

    init(interface: DetailProductViewProtocol, interactor: DetailProductInteractorInputProtocol?, router: DetailProductWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
