//
//  DetailProductInteractor.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductInteractor: DetailProductInteractorInputProtocol {
    func getDetail(barCode: String) {
        DBFirebaseHelper.shared.getDetailProduct(id: barCode) { listProduct in
            if let _listProduct = listProduct as? [ProductEntity] {
                 self.presenter?.didGetDetail(listProduct: _listProduct)
            }
        }
    }
    

    weak var presenter: DetailProductInteractorOutputProtocol?
}
