//
//  AddProductInteractor.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddProductInteractor: AddProductInteractorInputProtocol {
    func addProduct(product: ProductEntity) {
        DBFirebaseHelper.shared.addProduct(product: product)
    }
    
    weak var presenter: AddProductInteractorOutputProtocol?
}
