//
//  AddProductInteractor.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddProductInteractor: AddProductInteractorInputProtocol {

    weak var presenter: AddProductInteractorOutputProtocol?
}
