//
//  BranchProtocols.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BranchWireframeProtocol: class {

}
//MARK: Presenter -
protocol BranchPresenterProtocol: class {

    var interactor: BranchInteractorInputProtocol? { get set }
    func viewDidLoad()
}

//MARK: Interactor -
protocol BranchInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didGetBranch(listBranch: [BranchEntity])
}

protocol BranchInteractorInputProtocol: class {

    var presenter: BranchInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getBranch()
}

//MARK: View -
protocol BranchViewProtocol: class {

    var presenter: BranchPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetBranch(listBranch: [BranchEntity])
}
