//
//  BranchPresenter.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BranchPresenter: BranchPresenterProtocol, BranchInteractorOutputProtocol {
    func viewDidLoad() {
        interactor?.getBranch()
    }
    
    func didGetBranch(listBranch: [BranchEntity]) {
        view?.didGetBranch(listBranch: listBranch)
    }
    

    weak private var view: BranchViewProtocol?
    var interactor: BranchInteractorInputProtocol?
    private let router: BranchWireframeProtocol

    init(interface: BranchViewProtocol, interactor: BranchInteractorInputProtocol?, router: BranchWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
