//
//  BranchViewController.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BranchViewController: BaseViewController, BranchViewProtocol {
    func didGetBranch(listBranch: [BranchEntity]) {
        self.listBranch = listBranch
    }
    
    @IBOutlet weak var tbBranch: UITableView!

	var presenter: BranchPresenterProtocol?
    
    var listBranch = [BranchEntity]() {
        didSet {
            tbBranch.reloadData()
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTable()
        setTitleNavigation(title: "Chi Nhánh")
        presenter?.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.navigationBar.isHidden = false
    }

}

extension BranchViewController: UITableViewDelegate, UITableViewDataSource {
    
    func configureTable() {
        tbBranch.delegate = self
        tbBranch.dataSource = self
        tbBranch.registerXibFile(BranchCell.self)
        tbBranch.separatorStyle = .none
        tbBranch.backgroundColor = AppColor.main
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listBranch.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(BranchCell.self, for: indexPath)
        cell.branch = listBranch[indexPath.item]
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let width = UIScreen.main.bounds.width
        let height = width * 9/16
        
        return height
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let message = "Bạn chắc chắn đăng nhập vào \( listBranch[indexPath.item].key&) không?"
        DBFirebaseHelper.shared.branchMain = listBranch[indexPath.item]
        PopUpHelper.shared.showMessageOKCancel(message: message) {
            RouterService.shared.goToMain()
        }
    }
    
}
