//
//  BranchInteractor.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BranchInteractor: BranchInteractorInputProtocol {
    func getBranch() {
        DBFirebaseHelper.shared.getAllBranch { list in
            guard let branchs = list as? [BranchEntity] else { return }
            self.presenter?.didGetBranch(listBranch: branchs)
        }
    }
    

    weak var presenter: BranchInteractorOutputProtocol?
}
