//
//  SignOutInteractor.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/4/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignOutInteractor: SignOutInteractorInputProtocol {

    weak var presenter: SignOutInteractorOutputProtocol?
}
