//
//  SignOutViewController.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/4/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FirebaseAuth

class SignOutViewController: UIViewController, SignOutViewProtocol {

	var presenter: SignOutPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction func btnLogout() {
        try? Auth.auth().signOut()
        
        RouterService.shared.goToSignIn()
    }

}
