//
//  SignOutProtocols.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/4/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignOutWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignOutPresenterProtocol: class {

    var interactor: SignOutInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SignOutInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SignOutInteractorInputProtocol: class {

    var presenter: SignOutInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignOutViewProtocol: class {

    var presenter: SignOutPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
