//
//  SignOutRouter.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/4/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignOutRouter: SignOutWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignOutViewController(nibName: nil, bundle: nil)
        let interactor = SignOutInteractor()
        let router = SignOutRouter()
        let presenter = SignOutPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
