//
//  HomeViewController.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: BaseViewController, HomeViewProtocol {

	var presenter: HomePresenterProtocol?
    @IBOutlet weak var tbHome: UITableView!

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTable()
        setTitleNavigation(title: "Hàng Sắp Hết Hạn")
        
        let branch = BranchEntity(key: "TANTIEN", name: "Tân Tiến")
        let product = ProductEntity(id: "123456789", name: "Sữa Vinvamilk", dateCheck: 123456, dateExpire: 654321)
        DBFirebaseHelper.shared.addProduct(branch: branch, product: product)
    }
}

extension HomeViewController: UITableViewDelegate, UITableViewDataSource {
    func configureTable() {
        tbHome.registerXibFile(ProductCell.self)
        tbHome.delegate = self
        tbHome.dataSource = self
        tbHome.separatorStyle = .none
        
        tbHome.estimatedRowHeight = 150
        tbHome.rowHeight = UITableViewAutomaticDimension
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tbHome.dequeue(ProductCell.self, for: indexPath)
        
        return cell
    }
}
