//
//  HomeInteractor.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorInputProtocol {
    func getAllProductNeedCheck() {
        DBFirebaseHelper.shared.getProductNeedCheck(completion: { list in
            if let listProduct = list as? [ProductEntity] {
                self.presenter?.didGetProductNeedCheck(listProduct: listProduct)
            }
        })
       
    }

    weak var presenter: HomeInteractorOutputProtocol?
}
