//
//  HomeViewController.swift
//  BaseIOS2018
//
//  Created Ngoc Duong on 11/1/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: BaseViewController, HomeViewProtocol {
    
	var presenter: HomePresenterProtocol?
    @IBOutlet weak var tbHome: UITableView!
    
    var listProduct = [ProductEntity]() {
        didSet {
            tbHome.reloadData()
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTable()
        setTitleNavigation(title: "Hàng Sắp Hết Hạn")
        presenter?.viewDidLoad()
    }
}

extension HomeViewController: UITableViewDelegate, UITableViewDataSource {
    func configureTable() {
        tbHome.registerXibFile(ProductCell.self)
        tbHome.delegate = self
        tbHome.dataSource = self
        tbHome.separatorStyle = .none
        
        tbHome.estimatedRowHeight = 150
        tbHome.rowHeight = UITableViewAutomaticDimension
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listProduct.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tbHome.dequeue(ProductCell.self, for: indexPath)
        cell.product = listProduct[indexPath.item]
        cell.lbOrder.text = "\(indexPath.item + 1)"
        return cell
    }
}

// MARK: receive data
extension HomeViewController {
    func didGetProductNeedCheck(listProduct: [ProductEntity]) {
        self.listProduct = listProduct
    }
}
