//
//  SignInProtocols.swift
//  BaseIOS2018
//
//  Created Coby on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignInWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignInPresenterProtocol: class {

    var interactor: SignInInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SignInInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SignInInteractorInputProtocol: class {

    var presenter: SignInInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignInViewProtocol: class {

    var presenter: SignInPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
