//
//  SignInInteractor.swift
//  BaseIOS2018
//
//  Created Coby on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInInteractor: SignInInteractorInputProtocol {

    weak var presenter: SignInInteractorOutputProtocol?
}
