//
//  SignInPresenter.swift
//  BaseIOS2018
//
//  Created Coby on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInPresenter: SignInPresenterProtocol, SignInInteractorOutputProtocol {

    weak private var view: SignInViewProtocol?
    var interactor: SignInInteractorInputProtocol?
    private let router: SignInWireframeProtocol

    init(interface: SignInViewProtocol, interactor: SignInInteractorInputProtocol?, router: SignInWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func goToBranch() {
        router.goToBranch()
    }

}
