//
//  SignInRouter.swift
//  BaseIOS2018
//
//  Created Coby on 11/3/18.
//  Copyright © 2018 Ngoc Duong. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInRouter: SignInWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignInViewController(nibName: nil, bundle: nil)
        let interactor = SignInInteractor()
        let router = SignInRouter()
        let presenter = SignInPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goToBranch() {
        self.viewController?.navigationController?.pushViewController(BranchRouter.createModule(), animated: true)
    }
}
